// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xopmhqakfombqptdmyqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvcG1ocWFrZm9tYnFwdGRteXFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MzUyODcsImV4cCI6MjA2NjMxMTI4N30.lj_xwwjx5KBA8gB7yHrcAWpELvOtRxzf4Ttp9a3qGaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);